### ISSUE TITLE
Long-term goals

### ISSUE THREAD

**Issue by Ironholds** [forwards/presentations#1]
Not quite sure (because I've only got the slides, not the words that go around them!) what exactly was said/will be said, but - shouldn't we be aiming for higher involvement of women than CS? That is, our goal should be parity, intentionally, in gender terms (and any others).

**Comment by hturner** [comment]
The plan is to put a video of the talk on You Tube so you should get the opportunity to hear what was said. Meanwhile, I said something along the lines of "Some might say we should aim for equal numbers of men and women, however these women have to come from somewhere so what are realistic goals for what we can achieve?" Of course women do not need a CS background to be R developers, but surely the minimum we can expect is to have a similar proportion of women as in this field and we are not even there yet. So it is a first step to aim for I think and already challenging to achieve.

**Comment by Ironholds** [comment]
_nodnod_. Makes sense.

**Comment by hturner** [comment]
So closing issue for now, but it will be great if we can come back to this and aim higher further down the line.
